collections_config:
  docs:
    schemas:
      default:
        path: schemas/article.md
        icon: format_align_left
        name: Documentation Article
      guide:
        path: schemas/guide.md
        icon: article
        name: Help Guide

_inputs:
  title:
    comment: The main h1 on the page. Also used to build the page metadata.
  nav_title:
    comment: A (usually shorter) name to show in the left-hand navigation.
  nav_section:
    comment: The heading to place this page under in the left-hand navigation. Set to "Root" to place at the top level.
  weight:
    comment: Navigation weighting for this page. Lower weights will appear higher. Groups are sorted by the lowest weight within each group.
  guide_label:
    comment: Shown above the h1

_snippets:
  tree:
    inline: false
    template: hugo_paired_shortcode_positional_args
    definitions:
      shortcode_name: tree
      positional_args: []
      content_key: file_tree
    _inputs:
      file_tree:
        type: code
        comment: A tree of files. The character `>` will be replaced with the appropriate box drawing characters. Use a leading `+` on a line to highlight.
    preview:
      text: Diffable File Tree
      icon: account_tree
      subtext:
        - key: file_tree
        - File tree with automatic box drawing indentation
    picker_preview:
      gallery:
        image:
          - .cloudcannon/preview_images/tree.png
  custom_code:
    inline: false
    template: hugo_paired_shortcode_named_args
    definitions:
      shortcode_name: custom_code
      content_key: code_block
      named_args:
        - editor_key: lang
          type: string
        - editor_key: filename
          type: string
    _inputs:
      code_block:
        type: code
      lang:
        comment: Any language supported by [Hugo syntax highlighting](https://gohugo.io/content-management/syntax-highlighting/#list-of-chroma-highlighting-languages)
    preview:
      text: Rich code component
      icon: subtitles
      subtext:
        - key: filename
        - Expandable code block with labelled filename
    picker_preview:
      gallery:
        image:
          - .cloudcannon/preview_images/custom_code.png

_editables:
  content:
    blockquote: true
    bold: true
    format: p h1 h2 h3 h4 h5 h6 pre address div
    italic: true
    strike: true
    subscript: true
    superscript: true
    underline: true
    link: true
    bulletedlist: true
    indent: true
    numberedlist: true
    outdent: true
    code: true
    embed: true
    horizontalrule: true
    image: true
    table: true
    undo: true
    redo: true
    removeformat: true
    copyformatting: true
    image_size_attributes: true
    snippet: true

